
export default {
	SELECTED_FILTER: 'SELECTED_FILTER',
	START_COUNTER: 'START_COUNTER',
	REFRESH_COUNTER: 'REFRESH_COUNTER',
	STOP_COUNTER: 'STOP_COUNTER',
	ADD_ITEM: 'ADD_ITEM',
	LIST_ITEMS: 'LIST_ITEMS',
	CHANGE_NAME: 'CHANGE_NAME',
	CHANGE_TRACKER_NAME: 'CHANGE_TRACKER_NAME',
	REPLACE_ITEMS: 'REPLACE_ITEMS',
	TIME_SESSION_GET_URL: 'api/list/',
	TIME_SESSION_NEW_URL: 'api/new',
	TIME_SESSION_UPDATE_NAME_URL: 'api/update/'
}
